default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5

development:
  <<: *default
  database: rails_template_development
  username: root
  password: ""
  host: localhost

test:
  <<: *default
  database: rails_template_test
  username: root
  password: password
  host: 127.0.0.1
  port: 3306
  pool: 5
  timeout: 5000

staging:
  <<: *default
  database: <%= ENV['STAGING_DATABASE_NAME'] %>
  username: <%= ENV['STAGING_DATABASE_USERNAME'] %>
  password: <%= ENV['STAGING_DATABASE_PASSWORD'] %>
  host: <%= ENV['STAGING_DATABASE_HOST'] %>
  port: <%= ENV['STAGING_DATABASE_PORT'] %>

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  port: <%= ENV['PRODUCTION_DATABASE_PORT'] %>