default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root  # MySQL のユーザー名
  password: ""    # 必要に応じて設定
  host: localhost

development:
  <<: *default
  database: rails_template_development

test:
  adapter: mysql2
  encoding: utf8mb4
  database: rails_template_test
  username: root
  password: password
  host: mysql
  port: 3306
  pool: 5
  timeout: 5000


production:
  <<: *default
  database: rails_template_production
  username: myapp
  password: <%= ENV['DATABASE_PASSWORD'] %>